using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SavarankiskasDarbas.Repos
{
    internal class CompanyRepo
    {
        public List<Company> companies = new List<Company>();
        public CompanyRepo()
        {
            companies.Add(new Company(6007, "Grand Enterprises O.L Ltd.", 201));
            companies.Add(new Company(1328, "AV-EX AVIATION EXCELLENCE", 3));
            companies.Add(new Company(1329, "AVIA TECHNIQUE LTD.", 35));
            companies.Add(new Company(1330, "Aviall Services Inc.", 146));
            companies.Add(new Company(1331, "Air Atlanta Aviaservices LIMITED", 35));
            companies.Add(new Company(1332, "AVIATION EXCESS INC.", 3));
            companies.Add(new Company(1333, "AVIATION GRAPHIX  LTD", 202));
            companies.Add(new Company(1334, "AVIATION POWER INC.", 3));
            companies.Add(new Company(1335, "AVIATION SUPPORT EUROPE", 89));
            companies.Add(new Company(1336, "AVIATRONICS, INC.", 3));
            companies.Add(new Company(1337, "AVIO-DIEPEN B.V.", 146));
            companies.Add(new Company(1338, "AVION SYSTEMS, INC.", 3));
            companies.Add(new Company(1339, "AVIONIK STRAUBING VERTRIEBS UND SERVICE", 5));
            companies.Add(new Company(1340, "AVIOSERV SAN DIEGO, INC.", 3));
            companies.Add(new Company(1341, "AVIOSUPPORT", 3));
            companies.Add(new Company(1827, "Aircraft Support and Services, Inc.", 3));
            companies.Add(new Company(1362, "BIAERO, LLC", 3));
            companies.Add(new Company(1363, "BIC CARPETS", 89));
            companies.Add(new Company(1364, "BIGGLES LABELLING LIMITED", 35));
            companies.Add(new Company(1365, "BILL THOMAS ASSOCIATES, INC.", 3));
            companies.Add(new Company(1861, "WILSON AVIATION SERVICES", 3));
            companies.Add(new Company(1367, "BOMBARDIER AEROSPACE", 102));
            companies.Add(new Company(1368, "BOTRON COMPANY INC.", 3));
            companies.Add(new Company(1369, "BOURNEMOUTH AVIATION (CONSULTANTS) LTD.", 35));
            companies.Add(new Company(81, "Magnetic MRO AS", 125));
            companies.Add(new Company(1370, "BP OIL INTERNATIONAL LTD", 35));
            companies.Add(new Company(1371, "BRESLIN AEROTECH, LLC", 3));
            companies.Add(new Company(1372, "BRIDGES NDT", 35));
            companies.Add(new Company(1373, "BRIDGESTONE AIRCRAFT TIRE", 89));
            companies.Add(new Company(1375, "BRITANNIA AIRWAYS", 35));
            companies.Add(new Company(1376, "BRITISH AIRWAYS ENGINEERING", 35));
            companies.Add(new Company(1377, "BRITISH MIDLAND AIRWAYS LIMITED", 35));
            companies.Add(new Company(1378, "BROWN AVIATION TOOL SUPP", 3));
            companies.Add(new Company(1379, "BURWOOD AVIATION SUPPLIES LTD", 35));
            companies.Add(new Company(1380, "CABINAIR SERVICES", 35));
            companies.Add(new Company(1381, "CANJET - A DIVISION OF IMP GROUP LTD", 102));
            companies.Add(new Company(1382, "CARA AVIATION SERVICES", 3));
            companies.Add(new Company(1383, "CARLISLE INTERCONNECT TECHNOLOGIES", 3));
            companies.Add(new Company(1384, "CARPATAIR S.A.", 71));
            companies.Add(new Company(1385, "CASCADE AVIATION SERVICES INC.", 3));
            companies.Add(new Company(1386, "CATANA", 146));
            companies.Add(new Company(1387, "CFM MATERIALS LP", 3));
            companies.Add(new Company(1344, "AVTRON AEROSPACE, INC.", 3));
            companies.Add(new Company(1345, "AW-Tronics LLC", 91));
            companies.Add(new Company(1346, "AXA POWER", 120));
            companies.Add(new Company(1347, "B&H WORLDWIDE LTD", 35));
            companies.Add(new Company(1348, "B/E AEROSPACE", 146));
            companies.Add(new Company(1349, "B/E Aerospace Seats Aftermarket", 35));
            companies.Add(new Company(1350, "B/E AEROSPACE WINSTON SALEM, NC", 3));
            companies.Add(new Company(1351, "B/E AEROSPACE, INC.", 3));
            companies.Add(new Company(1352, "BAE SYSTEMS (Operations) Limited", 35));
            companies.Add(new Company(1353, "BAE SYSTEMS", 3));
            companies.Add(new Company(3089, "MJL Aircraft Parts Unipessoal, Lda", 75));
            companies.Add(new Company(1356, "BALLY RIBBON MILLS", 3));
            companies.Add(new Company(1357, "BALTIC FREIGHT SERVICES UAB", 1));
            companies.Add(new Company(1358, "BALTIC MAINTENANCE, UAB", 1));
            companies.Add(new Company(1359, "BARRY CONTROLS AEROSPACE", 136));
            companies.Add(new Company(1360, "B/E Aerospace Galley aftermarket", 35));
            companies.Add(new Company(1361, "BELAVIA", 100));
            companies.Add(new Company(3088, "BAUER AVIATION", 3));
            companies.Add(new Company(3100, "Electro Enterprises, Inc.", 3));
            companies.Add(new Company(3090, "BLACK SWAN CONSULTING INC.", 3));
            companies.Add(new Company(1301, "AKZONOBEL AEROSPACE COATINGS", 146));
            companies.Add(new Company(1302, "AFSR Aichach GmbH (Arconic)", 5));
            companies.Add(new Company(1303, "ALFA AVIATION SERVICES", 102));
            companies.Add(new Company(1304, "ALL METAL SERVICES LTD (AMS)", 35));
            companies.Add(new Company(1305, "AMERICAN SUN COMPONENTS INC.", 3));
            companies.Add(new Company(1306, "AMETEK (MUIRHEAD)", 35));
            companies.Add(new Company(1307, "AMI METALS, INC.", 3));
            companies.Add(new Company(1308, "AMSAFE AVIATION", 35));
            companies.Add(new Company(1309, "Aftermarket Spares and Services Ltd ", 35));
            companies.Add(new Company(1310, "ANGLIA NDT LIMITED", 35));
            companies.Add(new Company(1311, "ANKER-TEPPICHBODEN", 5));
            companies.Add(new Company(1312, "ANSETT AIRCRAFT SPARES AND SERVICES", 35));
            companies.Add(new Company(1313, "APELLA S.A.", 214));
            companies.Add(new Company(1314, "API - AEROSPACE PRODUCTS INTERNATIONAL", 3));
            companies.Add(new Company(1315, "APPLIED HEAT", 3));
            companies.Add(new Company(1316, "APS AIR PARTS SERVICES & SUPPLIES LTD.", 201));
            companies.Add(new Company(1317, "APS AIRPARTS SUPPORT, INC", 3));
            companies.Add(new Company(1318, "ASSOCIATED SALES INTERNATIONAL", 3));
            companies.Add(new Company(1319, "ATC LASHAM", 35));
            companies.Add(new Company(1320, "ATELIERS BIGATA", 136));
            companies.Add(new Company(1321, "ATLANTIC JET SUPPORT", 3));
            companies.Add(new Company(1322, "ATM PP SP.Z O.O.", 224));
            companies.Add(new Company(1325, "AUSTRIAN AIRLINES", 16));
            companies.Add(new Company(1323, "ATR - AVIONS DE TRANSPORT REGIONAL", 136));
            companies.Add(new Company(1324, "AURELA, UAB", 1));
            companies.Add(new Company(1915, "CAPITAL AEROSPARES, Inc dba CAS AVIATION", 3));
            companies.Add(new Company(1916, "Aero-Zone, Inc", 3));
            companies.Add(new Company(1950, "HELIPONENTS, INC.", 3));
            companies.Add(new Company(1951, "CALSTAR", 3));
            companies.Add(new Company(1952, "AIRWORK NEW ZEALAND LIMITED", null));
            companies.Add(new Company(1953, "ALARIS AEROSPACE SYSTEMS LLC.", 3));
            companies.Add(new Company(1954, "HONG KONG LIBERTY AVIATION SERVICES.", 3));
            companies.Add(new Company(1955, "IAS INDUSTRIAL & AIRBORNE SYSTEMS", 5));
            companies.Add(new Company(1956, "JOY AVIATION CORP.", 3));
            companies.Add(new Company(1957, "BANYAN AIR SERVICE", 3));
            companies.Add(new Company(1900, "OTTO INSTRUMENT SERVICE, INC.", 3));
            companies.Add(new Company(1901, "GIMA AEROSPACE", 154));
            companies.Add(new Company(1902, "SR Technics Switzerland", 106));
            companies.Add(new Company(1903, "AVP AERO VOO PORTUGAL LDA", 75));
            companies.Add(new Company(1904, "GA Telesis, LLC", 3));
            companies.Add(new Company(1907, "STAR TECH AVIATION CO.,LTD. ", 209));
            companies.Add(new Company(1928, "SEICO Technology Ltda", 111));
            companies.Add(new Company(1929, "AERSALE, INC Corporate Headquarters", 3));
            companies.Add(new Company(2974, "AWAS.", 202));
            companies.Add(new Company(1931, "FIRST CLASS AIR REPAIR", 3));
            companies.Add(new Company(1932, "TRIUMPH INTERIORS LLC", 3));
            companies.Add(new Company(1958, "EXECUTIVE JET SUPPORT, LTD.", 35));
            companies.Add(new Company(166, "BOEING CO", 3));
            companies.Add(new Company(1970, "RELIABLE JET MAINTENANCE", 3));
            companies.Add(new Company(1971, "HELICOPTER SPARES CORP", 3));
            companies.Add(new Company(1972, "FLORIDA JET PARTS LLC", 3));
            companies.Add(new Company(1973, "FORELAND AVIATION SA", 20));
            companies.Add(new Company(1974, "ALTERNATIVE AVIATION SERVICES", 3));
            companies.Add(new Company(1975, "GLOBAL AIRPARTS", 3));
            companies.Add(new Company(1976, "QUALITY AVIATION INSTRUMENTS, INC.", 3));
            companies.Add(new Company(1977, "SKYMASTERS AVIATION, LLC", 3));
            companies.Add(new Company(1978, "STARWARES.", 3));
            companies.Add(new Company(1979, "AERO HARDWARE & PARTS COMPANY INC", 3));
            companies.Add(new Company(1980, "FASTENER DIMENSIONS INC.", 3));
            companies.Add(new Company(1981, "UFC AEROSPACE CORP NY", 3));
            companies.Add(new Company(1982, "JET INTERNATIONAL COMPANY L.L.C.", 3));
            companies.Add(new Company(1983, "AIRCRAFT HARDWARE WEST, INC.", 3));
            companies.Add(new Company(1984, "TAB HARDWARE, INC.", 3));
            companies.Add(new Company(1985, "Continental Aircraft Support, Inc", 3));
            companies.Add(new Company(1864, "SPIRIT AVIATION SERVICES INC", 3));
            companies.Add(new Company(1866, "ITUM CORP", 3));
            companies.Add(new Company(1867, "WORLD AVIATION LOGISTICS LLC.", 3));
        }
    }
}
